### ISSUE TITLE
Pnpm CLI option not recognized

### ISSUE THREAD

**Issue by KoutouQC** [dependency-check/DependencyCheck#3789]
**Describe the bug**
The new cli option for pnpm and disablePnpmAudit are not recognized on the cli.

**Version of dependency-check used**
The problem occurs using version 6.5.0 of the cli.

**Log file**
>Unrecognized option: --pnpm

**To Reproduce**
1. Download latest release (windows or Linux)
2. Install
3. .\dependency-check.bat --version
4. output: `Dependency-Check Core version 6.5.0`
3. .\dependency-check.bat --pnpm c:\path -s C:\secondpath
4. output: `Unrecognized option: --pnpm`

**Expected behavior**
I expect both --pnpm and  --disablePnpmAudit to be recognized by the CLI.

**Additional context**
```shell
>.\dependency-check.bat --disablePnpmAudit
Unrecognized option: --disablePnpmAudit
```

**Comment by adcorduneanu** [comment]
I would say there is more related to this issue because my entire Azure DevOps pipeline is failing with the following exception:

[ERROR] Exception occurred initializing Pnpm Audit Analyzer.
...
[ERROR] Unable to read pnpm audit output.

##[debug]2 final results
[ 'Source\\dep\\dependency-check-report.html',
  'Source\\dep\\dependency-check-report.json' ]
Dependency Check failed with message "Dependency Check exited with an error code (exit code: 4294967282)."
##[debug]task result: Failed
##[error]Dependency Check exited with an error code (exit code: 4294967282).

So means something is there, but not everything...

**Comment by bovy89** [comment]
the option `--disablePnpmAudit` is still not recognized on the cli.

```
$ ./dependency-check.sh --version
Dependency-Check Core version 6.5.3

$ ./dependency-check.sh --disablePnpmAudit
Unrecognized option: --disablePnpmAudit
```

**Comment by KoutouQC** [comment]
There's a workaround. You can set it via env variables.

```bash
JAVA_TOOL_OPTIONS=-Danalyzer.pnpm.path=/your/path
```

**Comment by ssaturno** [comment]
Hello, I'm trying to execute the command  '--disablePnpmAudit' as an argument  in my Dependency Check task in a pipeline from Azure DevOps and it doesn't work.

I get this:
[ERROR] Exception occurred initializing Pnpm Audit Analyzer.
[ERROR] Unable to read pnpm audit output.

I read the bug is already fixed but I'm having it yet.

Any suggestion?

**Comment by kristofertreutwein** [comment]
--disablePnpmAudit is still not a recognized option to the cli in 6.5.3

proposal would be 
[issue3789-disablepnpm.patch.txt](https://github.com/jeremylong/DependencyCheck/files/7917827/issue3789-disablepnpm.patch.txt)
