### ISSUE TITLE
NVD API & Proxy Issues

### ISSUE THREAD

**Issue by ben-vanderlinde** [dependency-check/DependencyCheck#6127]
Process hangs indefinately (so far during update when updating via a proxy server (using proxyserver & proxyport arguments).
No traffic is observed on the proxy server.

The problem occurs using version 9.0.0 of the cli (windows)

We initially observed this behaviour while running the dependency check in our build pipelines in an azure devops task, and the task hangs at 'Checking for updates'. In this instance it hung for over 20 hours before I manually cancelled it. No connection attempts to services.nvd.nist.gov were logged by our proxy server :
https://gist.github.com/ben-vanderlinde/78862735eb6da114523381448c4838a8

Testing from the command line locally, but using a local instance of fiddler as the proxy server I get the same result:
Fiddler does not report any connection attempts either :
https://gist.github.com/ben-vanderlinde/3fec12de3f9a639d520fb11593d2ebe7

1. Run the following fromthe cli on a windows machine :
.\dependency-check.bat --updateonly --proxyserver {proxy_server_hostname} --proxyport {proxy_server_port} --nvdApiDelay 1000 --nvdApiKey {nvdApiKey}
2. Wait for a long time and observe no error output, and no traffic on the proxy.

It should attempt to connect to the NVD api via the proxy server to fetch updates.
In the event the NVD api is unreachable or returns an error code, the process should exit with an error code, and log the nature of the error.

**Comment by ben-vanderlinde** [comment]
Note : After some further testing, it appears it is simply ignoring the --proxyserver & --proxyport arguments, and attempting to connect directly. When run in an environment where outbound traffic is dropped by a firewall, this then leads to the hanging behaviour.

**Comment by goldzahn** [comment]
I have the same problem after migration to 9.0.0 using cli.
I have been using cli for years successfully behind a proxy server and now in the debug I can see the following:

Setting: proxy.server='Our Proxy IP'
Setting: proxy.port='8080'
BUT also:
java.net.UnknownHostException: services.nvd.nist.gov

So the proxy settings are clearly being ignored while trying to connect to services.nvd.nist.gov

We use openjdk version "1.8.0_392"

**Comment by Spanish93** [comment]
Same problem here, not working with proxy parameters.
Go back to 8.4.3

**Comment by humblekofe** [comment]
Hi, I'm using the maven-plugin where I have experienced the same problem until I realized that I have to configure an http**s** proxy by using:
-Dhttps.proxyHost=myinternalproxy.com -Dhttps.proxyPort=80
as the requests go to https://services.nvd.nist.gov:443 and use https.

**Comment by Spanish93** [comment]
CLI only have --proxyser and --proxyport.
As reported by others, these arguments are ignored. No trafic is send to the proxy.

It's perfect working with old version like 8.4.2 or 8.4.3.
KEV URL it's also Https and no issue with old version of dependency check.

It's a blocking bug, people using proxy can't move to last version.

**Comment by jeremylong** [comment]
Yes - 9.0.0 is likely having issues with proxy connection.  We need to resolve #6107 before worrying about the proxy issue.

**Comment by jeremylong** [comment]
if you are behind a proxy and by default the proxy configuration is not working - please try setting the default Java proxy configuration using JAVA_TOOL_OPTIONS (see https://docs.oracle.com/javase/8/docs/technotes/guides/net/proxies.html)
- https.proxyHost
- https.proxyPort
- https.proxyUser
- https.proxyPassword
- http.nonProxyHosts

This **should** work. If it does I will update the documentation and remove the no longer used configuration options.

**Comment by Spanish93** [comment]
Ok, I'll look how to do that using the Jenkins plugins. I don't want to edit the .sh inside your release package to add that.

**Comment by jeremylong** [comment]
JAVA_TOOL_OPTIONS is an environment variable you can set.

**Comment by ben-vanderlinde** [comment]
Configuring the proxy settings in the JAVA_TOOL_OPTIONS seems to have resolved proxy issue for us.
 Note the format of the proxy host has changed fromt the CLI arguments in that you need to drop the protocol prefix 'http://', and just give the hostname of the proxy server.

JAVA_TOOL_OPTIONS="-Dhttps.proxyHost={proxyHost} -Dhttps.proxyPort={proxyPort}"

**Comment by goldzahn** [comment]
JAVA_TOOL_OPTIONS="-Dhttps.proxyHost={proxyHost} -Dhttps.proxyPort={proxyPort}"

Resolved the issue also for us. Thanks.

**Comment by Spanish93** [comment]
Same here, no more problem with proxy, now only a lot of 504. But not related to this problem

**Comment by jeremylong** [comment]
Most issues with the NVD API have been resolved with 9.0.2. However, we still have a few things to update regarding proxy configuration.

1. Remove old/unused configuration settings
2. Document the use of core java proxy configuration (see https://github.com/jeremylong/DependencyCheck/issues/6127#issuecomment-1826773121)
3. Ensure item 2 above actually works with proxy authentication and if not, update the code so that it works.

**Comment by platformbeheer-otv** [comment]
> JAVA_TOOL_OPTIONS

How to set the JAVA_TOOL_OPTIONS in the Azure DevOps task dependency-check-build-task@6? You might want to mention this in the documentation, not a lot of people know about the env option:

```
- task: dependency-check-build-task@6
  displayName: 'Dependency Check'
  inputs:
    projectName: $(System.TeamProject).$(Build.Repository.Name)
    scanPath: '$(System.DefaultWorkingDirectory)\packages'
    format: ALL
    reportsDirectory: '$(Common.TestResultsDirectory)'
    additionalArguments: '--nvdApiKey $(DEPENDENCY_CHECK_NVDAPIKEY)'
    localInstallPath: '$(DEPENDENCY_CHECK_LATEST)'   
  env:
    JAVA_TOOL_OPTIONS: "-Dhttps.proxyHost=XXX -Dhttps.proxyPort=XXX -Dhttp.nonProxyHosts=XXX"
```

**Comment by kornefalk** [comment]
If you already have proxy configuration in the environment (https_proxy=http://myproxy:port) , you can use (source https://vpavic.github.io/proxy-guidelines/)
`JAVA_TOOL_OPTIONS="-Djava.net.useSystemProxies=true"`

**Comment by platformbeheer-otv** [comment]
> If you already have proxy configuration in the environment (https_proxy=http://myproxy:port) , you can use (source https://vpavic.github.io/proxy-guidelines/) `JAVA_TOOL_OPTIONS="-Djava.net.useSystemProxies=true"`

Keep in mind that the nonProxyHosts will probably give you issues because the separator is not standardized and depending on the implementation it might not work :-(
See: https://about.gitlab.com/blog/2021/01/27/we-need-to-talk-no-proxy/

**Comment by ArnaudLec** [comment]
> If you already have proxy configuration in the environment (https_proxy=http://myproxy:port) , you can use (source https://vpavic.github.io/proxy-guidelines/) `JAVA_TOOL_OPTIONS="-Djava.net.useSystemProxies=true"`

Thanks a lot. I do not have a system proxy configuration for various reasons and tried with `JAVA_TOOL_OPTIONS: "-Dhttp.proxyHost=XXX -Dhttp.proxyPort=XXX"` without success until reading you.
But also adding the proxy as an env variable works for me :
```
HTTP_PROXY="http://proxyhost:proxyport"
JAVA_TOOL_OPTIONS="-Djava.net.useSystemProxies=true"
```

**Comment by ultramaks** [comment]
Had [the same issue](https://github.com/jeremylong/DependencyCheck/issues/6149#issuecomment-1838449815) in .gitlab-ci.yml using proxy. Fixed by this setting before running checks
_- export JAVA_TOOL_OPTIONS="-Dhttps.proxyHost=xxx -Dhttps.proxyPort=XXX"_

**Comment by jeremylong** [comment]
If using proxy auth - this will be fixed in 9.0.3.

**Comment by ultramaks** [comment]
> If using proxy auth - this will be fixed in 9.0.3.

no any auth, just using proxy to get into Internet (no username/password)

**Comment by chinzzz** [comment]
> if you are behind a proxy and by default the proxy configuration is not working - please try setting the default Java proxy configuration using JAVA_TOOL_OPTIONS (see https://docs.oracle.com/javase/8/docs/technotes/guides/net/proxies.html)
> 
> * https.proxyHost
> * https.proxyPort
> * https.proxyUser
> * https.proxyPassword
> * http.nonProxyHosts
> 
> This **should** work. If it does I will update the documentation and remove the no longer used configuration options.

hello @jeremylong, does this also supposed to work for an http proxy? (it also does not require username and password) I tried different configurations already including adding them as JAVA_TOOL_OPTIONS, in plugin's configuration section, and as part of the maven goal but nothing works. I am still getting:

NVD API request failures are occurring; retrying request for the nth time 
Recoverable I/O exception (org.apache.hc.client5.http.HttpHostConnectionExceptionn) caught when processing request to {s}->https://services.nvd.nist.gov:443
